### PR TITLE
Update role for work with InfluxDB 1.2.0

### PR DESCRIPTION
**Pull request by popstas**
Before config template describe:

`default/main.yml`: changed influxdb_install_method to 'repository',
i think that repo inslall is preferred way for most cases.

`handlers/main.yml`: renamed service from 'influxdb' to 'influxd'.

`tasks/install-download.yml`: added checksum check and changed url template.
Added package 'ca-certificate', see https://github.com/ansible/ansible/issues/9966#issuecomment-282464669

`tasks/main.yml`: merged 4 create directory tasks to one.

## Upgrade config template to v1.2.0

I've compared default config from influxdb v1.2.0 with template and updated template.
I also updated all comments and leaved commented default values for better diff.

New variables not described bellow, see commit.

Deletes and changes:

v0.12
Some configuration parameters from [meta] and [data] was removed. Commits:
- https://github.com/influxdata/influxdb/commit/22173acb707af833b832126f8631e0afda445ea9
- https://github.com/influxdata/influxdb/commit/686d1a7ba4c06b407117157a00df774e9203b095

v1.0.0:
Config option [cluster] has been replaced with [coordinator]

Section [hinted-handoff] was removed.

### Updated defaults:
hostname = "localhost" # Ansible 2.2 with ansible_default_ipv4.address fires AnsibleUndefinedVariable: {{ ansible_default_ipv4.address }}: 'ansible_default_ipv4' is undefined

[data]
cache-max-memory-size = 1048576000
cache-snapshot-write-cold-duration = "10m"
compact-full-write-cold-duration = "4h"

[coordinator]
write-timeout = "10s"

[admin]
enabled = false

[http]
pprof-enabled = true

[[graphite]]
batch-size = 5000
batch-pending = 10

[[collectd]]
batch-size = 5000
batch-timeout = "10s"

[[opentsdb]]
certificate= "/etc/ssl/influxdb.pem"

[[udp]]
bind-address = ":8089"
batch-size = 5000
batch-pending = 10

## Verify
I tested role on local gitlab-ci, Travis now down due Amazon S3 issues.
Ansible 2.2, tested on ubuntu:latest docker image.
Tested both `download` and `repository` methods.

### CODE REVIEW

**Comment by popstas** [comment]
I fixed tests, but Travis don't pushed results here.
Link to build history - https://travis-ci.org/viasite-ansible/ansible-role-influxdb/builds

**Comment by mtchavez** [comment]
Thanks a lot. Looks good. Re-ran the tests on travis because there was a failure with the template loading. Not sure why the checks didn't/aren't showing up on the pull request. Going to merge this in as is and make an updated release to Galaxy.

**Comment by popstas** [comment]
Forgot change version on top of README.md from 0.9 to 1.2, can you change it?

**Comment by mtchavez** [comment]
Updated to v6.0.0 in Galaxy. Thanks again.

**Pull request merged**
